### PR TITLE
Refactored MPPI configuration

### PR DESCRIPTION
**Pull request by luisenp**
## Types of changes
Refactors controller configuration so that it's easy to swap action optimizers. 

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context / Related issue
Cleans up some of the code in #119

## How Has This Been Tested (if it applies)
I also modified `control_env.py` to easily swap CEM for MPPI. I tested it on HalfCheetah-v2 and Humanoid-v2, and it seems to have very similar performance to CEM. 

## Checklist

- [x] The documentation is up-to-date with the changes I made.
- [x] I have read the [**CONTRIBUTING**](../../CONTRIBUTING.md) document and completed the CLA (see **CONTRIBUTING**).
- [x] All tests passed, and additional code has been covered with new tests.

### CODE REVIEW

**Comment by luisenp** [comment]
Hi @freiberg-roman. Any comments on this? Merging into the `mbrl` master branch seems fine to me, just looking to see if you had any comments.

**Comment by freiberg-roman** [comment]
Sorry for the late reply. I am currently on vacation without WiFi. I will be back on 14.08 (tomorrow) and take a look :)

**Comment by luisenp** [comment]
Sounds good, enjoy your vacation!

**Review by freiberg-roman — APPROVED** [review]

**Comment by freiberg-roman** [comment]
Thanks for the cleanup! These changes all seem to work.

**Pull request merged**
